In [21]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
# calculate accuracy measures and confusion matrix
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score, auc
from sklearn.metrics import roc_curve, auc
# importing ploting libraries
import matplotlib.pyplot as plt   
#importing seaborn for statistical plots
import seaborn as sns
# To enable plotting graphs in Jupyter notebook
%matplotlib inline 
from sklearn.neighbors import KNeighborsClassifier

In [20]:
def modelPerformanceAnalysis(X, y, model, test_size = 0.3, seed = 7):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
    model.fit(X_train, y_train)
    ### Unoptimized probability threshold based performance numbers
    # Train accuracy numbers
    trainPreds = model.predict(X_train)
    trainAccuracy = accuracy_score(y_train, trainPreds)
    trainRecall = recall_score(y_train, trainPreds)
    trainPrecision = precision_score(y_train, trainPreds)
    trainF1score = f1_score(y_train, trainPreds)
    trainResults=[X_train.shape[0], trainAccuracy, trainRecall, trainPrecision, trainF1score]
    # Test accuracy numbers
    testPreds = model.predict(X_test)
    testAccuracy = accuracy_score(y_test, testPreds)
    testRecall = recall_score(y_test, testPreds)
    testPrecision = precision_score(y_test, testPreds)
    testF1score = f1_score(y_test, testPreds)
    testResults=[X_test.shape[0], testAccuracy, testRecall, testPrecision, testF1score]
    resultsDf = pd.DataFrame( index=["dataSize", "accuracy", "recall", "precision", "f1_score"])# Concatenate Train and Test results to resultsDf
    resultsDf['trainResults'] = trainResults
    resultsDf['testResults'] = testResults
    
    return resultsDf.round(2)

In [4]:
pl_df = pd.read_csv( 'Bank_Personal_Loan_Modelling.csv' )

In [6]:
pl_df.head(5)

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [7]:
pl_df.shape

(5000, 14)

# 2. Study the data distribution in each attribute, share your findings.

In [19]:
pl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [ ]:
All the values given are numeric and non-null values. Target column is "Personal Loan".

# 3. Get the target column distribution. Your comments

In [ ]:
"Personal Loan" is the target column. This column tells whether the person is opting for the perosnal loan or not.
As Bank want to increse the loan purchage. So "Personal Loan" is the target column.

# 4. Split the data into training and test set in the ratio of 70:30 respectively

In [17]:
pl_df = pd.get_dummies(pl_df, drop_first=True)
X = pl_df.drop('Personal Loan', axis=1)
y = pl_df[['Personal Loan']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 , random_state=5)

# 5. Use different classification models (Logistic, K-NN and Naïve Bayes) to predict the likelihood of a liability customer buying personal loans

In [91]:
# Logistic regression performance analysis
lrModel = LogisticRegression()
modelPerformanceAnalysis(X, y, lrModel, 0.3, 47)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

           trainResults  testResults
dataSize        3500.00      1500.00
accuracy           0.90         0.92
recall             0.33         0.41
precision          0.53         0.52
f1_score           0.41         0.46

In [83]:
# K-NN Model performance analysis
knn = KNeighborsClassifier(n_neighbors=3)
modelPerformanceAnalysis(X, y, knn, 0.3, 17)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

           trainResults  testResults
dataSize        3500.00      1500.00
accuracy           0.93         0.89
recall             0.28         0.05
precision          0.80         0.32
f1_score           0.41         0.09

In [71]:
#Naive bayes model performance analysis
nbModel = GaussianNB()
modelPerformanceAnalysis(X, y, nbModel, 0.3, 53)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

           trainResults  testResults
dataSize        3500.00      1500.00
accuracy           0.89         0.90
recall             0.58         0.61
precision          0.44         0.50
f1_score           0.50         0.55

# 6. Print the confusion matrix for all the above models

In [31]:
def modelConfusionMatrix(X_train, y_train, model): 
	model.fit(X_train, y_train)
	y_predict = model.predict(X_test)
	metrics.confusion_matrix(y_predict, y_test)
	return metrics.confusion_matrix(y_predict, y_test)

In [52]:
# Logistic regression model confusion matrix
modelConfusionMatrix(X_train, y_train, lrModel)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[1317,  101],
       [  34,   48]])

In [53]:
# K-NN Model confusion matrix
modelConfusionMatrix(X_train, y_train, knn)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

array([[1349,  144],
       [   2,    5]])

In [54]:
#Naive bayes model confusion matrix
modelConfusionMatrix(X_train, y_train, nbModel)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[1239,   67],
       [ 112,   82]])

# 7. Give your reasoning on which is the best model in this case and why it performs better?

In [ ]:
Based on the above results f1_score is giving better results for "Naive bayes" model with an accuracy of 0.9 and f1_score of 0.5.